### ISSUE TITLE
在处理 resolve(thenable) 时，还是和es6 promise 不一样的

### ISSUE THREAD

**Issue by HenryZhu-1988** [lfp1024/promise#4]
new Promise(resolve => {
  let resolvedPromise = Promise.resolve()
  resolve(resolvedPromise)
}).then(() => {
  console.log('resolvePromise resolved')
})

Promise.resolve()
  .then(() => { console.log('promise1') })
  .then(() => { console.log('promise2') })
  .then(() => { console.log('promise3') })

**Comment by lfpdev** [comment]
@JoMartinezZhu
修改了一下，resolve 解析 resolvedPromise 应该是异步调用 resolvedPromise 的then方法，导致多走了一轮。
https://github.com/lfp1024/promise/blob/master/test/promise-interview/q2.js
